baseURL = 'https://blog.edward-li.com/'
languageCode = 'en-us'
title = "Edward Li's Blog"
copyright = "Edward Li"
theme = 'hydra'

# Markdown Configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# RSS Configuration
[outputs]
  home = ["html", "rss"]
  section = ["html"]

[outputFormats.RSS]
  mediaType = "application/rss+xml"
  baseName = "index"
  isPlainText = true
  notAlternative = true

[[menu.main]]
name = "Blogs"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "Home"
url = "https://edward-li.com/"
weight = 4

[params]
colortheme = "white"
logo = "images/logo.png"
description = """I'm Edward Li, a Computer Science and Physics student at the [University of British Columbia](https://www.ubc.ca)!

Previously, I worked at [Google](https://www.google.com)/[GCP](https://cloud.google.com) scaling OpenTelemetry within first-party teams, at [Codegen](https://codegen.com/) building software agents and language servers, at [HP](https://www.hp.com) on high-performant remote work software, and at [Nokia](https://www.nokia.com) creating distributed testing frameworks for fiber optic systems.

I also play CTFs with [MapleBacon](https://maplebacon.org) and [MMM](https://x.com/mmm_ctf_team), build rockets with [UBC Rocket](https://www.ubcrocket.com), organize logistics for [nwPlus](https://nwplus.io), and foster communities at [Atelier](https://www.instagram.com/atelier.place/)/[Socratica](https://www.socratica.info).

This blog serves as a collection of my thoughts, projects, and experiences over the years. Feel free to explore!"""
mainSectionTitle = "Blog Posts"
mainSections = ["tech", "meta"]
displayCategories = ["tech", "meta"]
showAllPostsArchive = true
showAllPostsOnHomePage = true
enableBlogCategoryHeaders = true
themeFooter = true
rss = true

plausibleDomain = "blog.edward-li.com"
plausibleDataAPI = "https://a.dragondragondragon.xyz/api/event"
plausibleURL = "https://a.dragondragondragon.xyz/main.js"

[[params.social]]
  name = "github"
  link = "https://github.com/edwardjxli"

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/edwardjxli"

[[params.social]]
  name = "x-twitter"
  link = "https://x.com/edwardjxli"

[[params.social]]
  name = "bluesky"
  link = "https://bsky.app/profile/edward-li.com"

[[params.social]]
  name = "instagram"
  link = "https://www.instagram.com/edwardjxli"

[[params.social]]
  name = "discord"
  link = "https://discord.gg/9QF2bPc"

[[params.social]]
  name = "email"
  link = "blog@edward-li.com"

[services]
  [services.googleAnalytics]
    ID = 'G-BJ8JV88MMC'
